### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by hashitha** [WPF-Forge/Forge.Forms#10]
I keep getting the following build errors

![image](https://user-images.githubusercontent.com/10569142/36361644-abba10a4-1568-11e8-806f-2cd337690108.png)

![image](https://user-images.githubusercontent.com/10569142/36361655-b7936056-1568-11e8-806d-e4ac5250106c.png)

**Comment by redbaty** [comment]
Have you tried to uninstall and install the proxier package again? Can you check the project's target .NET framework

**Comment by hashitha** [comment]
I am using 4.6.1. I think package Nanoid doesn't support 4.6? I also removed proxier but where do I add it again from?

**Comment by redbaty** [comment]
@hashitha Proxier you can add it back using NuGet. If it still fails try targeting 4.7.1

**Comment by EdonGashi** [comment]
Is the NuGet of the main library published? It's time to split each project into their own repository with their own demo. Worrying about dependencies people may not even care about is extremely inconvenient...

**Comment by hashitha** [comment]
I don't have .net 4.7.1 only 4.6.2 I will try to download it and see if I can compile it tomorrow

**Comment by EdonGashi** [comment]
@hashitha Could you try building branch package-splitting? I removed a ton of unnecessary references from the demo. Each project will have their own app in their respective repository.

**Comment by hashitha** [comment]
@EdonGashi excellent I can build the demo on branch package-splitting now.

**Comment by redbaty** [comment]
I'll close this out since this seems to be fixed on the package-splitting branch, and since the project will be splat into multiple repos this shouldn't happen anymore
