### ISSUE TITLE
Dynamic form support for images

### ISSUE THREAD

**Issue by hashitha** [WPF-Forge/Forge.Forms#16]
I have now implemented most of the dynamic forms which seem to be working well.
I had a look at the code and couldn't find support for images. Is it possible to add support to load a jpg or png file?

I want to create a form similar to this one
![image](https://user-images.githubusercontent.com/10569142/40871867-9dbcf41c-6676-11e8-87c3-b38cd0abeebb.png)

**Comment by hashitha** [comment]
This is another example.
![image](https://user-images.githubusercontent.com/10569142/40871912-576702ea-6677-11e8-9965-41d7f1dc8adc.png)

**Comment by EdonGashi** [comment]
Shouldn't be hard, I'll do some quick experiments and I'll let you know

**Comment by EdonGashi** [comment]
I pushed master

```xml
<img src="captcha.png" />
```

```csharp
[Image("captcha.png")]
```

These are the requirements for src
- Value can be a string representing a path (I think even http works)
- Value can be an ImageSource, which is displayed as is
- Value can be a dynamic resource that resolves to a string or an ImageSource, if it's a string go to step 1, if it's an ImageSource go to step 2

I haven't tested it as an inline element to see how it looks, but I think we need to be able to support aligning and size properties of the image. Maybe we should allow an overriden `<img width=... height=... align="left|center|right">`

**Comment by EdonGashi** [comment]
Inline looks good!

![image](https://user-images.githubusercontent.com/12145268/40872977-22c4f598-6658-11e8-85d3-f1dafbdf180b.png)

**Comment by hashitha** [comment]
It works well. Looks like we need to allow  <img width=... height=... align="left|center|right">

**Comment by EdonGashi** [comment]
I was working on that. layout is crucial for images.

I added these attributes:

```xml
<img src="..." 
    width="auto|number"
    height="auto|number" 
    align="left|center|right|stretch" 
    valign="top|center|bottom|stretch" 
    stretch="none|fill|uniform|uniformtofill" 
    direction="both|uponly|downonly" />
```

Defaults:
```
width = auto
height = auto
align = stretch
valign = center
stretch = uniform
direction = downonly
```

Note: if you need to make an image bigger you need to change direction

**Comment by hashitha** [comment]
This works well and it also works with an URL as an image source.
