### ISSUE TITLE
Printing a form

### ISSUE THREAD

**Issue by hashitha** [WPF-Forge/Forge.Forms#22]
Is it possible to print a form?

**Comment by redbaty** [comment]
Hmm I dont think this is strictly related to forge.forms, maybe search for something related to wpf itself? I'll check it out later

**Comment by EdonGashi** [comment]
Check XML examples route in demo. I followed [this article](https://www.c-sharpcorner.com/UploadFile/mahesh/printing-a-control-in-wpf-using-C-Sharp/).

![image](https://user-images.githubusercontent.com/12145268/41236509-9baf0148-6d91-11e8-887f-f851744319bd.png)

You probably need to fiddle with the settings but it's definitely possible. You could also add an Env flag `print` or something, such that when it's set you can hide buttons `visible="!{Env printing}"`.

**Comment by hashitha** [comment]
Thanks! @EdonGashi  I will give this a try

**Comment by hashitha** [comment]
This works well
