### ISSUE TITLE
Extra data for checkboxes

### ISSUE THREAD

**Issue by hashitha** [WPF-Forge/Forge.Forms#26]
Is there any way we can attach extra details for checkboxes so we can retrieve these in the JSON data.

something like this
```
 <input
    type="bool"
    name="is-PancreasAbnormal"
    uncheckedText="Pancreas is normal"
    checkedText="Pancreas is abnormal and shows echogenicity"
    label="Abnormal Echogenicity"></input>
```

then the final JSON object would look like the following if the checkbox is ticked
```
{
  "is-PancreasAbnormal": {
    "value": true,
    "text": "Pancreas is abnormal and shows echogenicity"
  },
  "LastName": "doe",
  "DateOfBirth": "2018-10-08T00:00:00"
}
```

**Comment by hashitha** [comment]
I can't get this to work.

This is my current code to convert to JSON

```
 public void HandleAction(IActionContext actionContext)
{
  ExpandoObject formDataObject = (actionContext.Model as ExpandoObject);
  dynamicFormData = Newtonsoft.Json.JsonConvert.SerializeObject(formDataObject);
}
```

if I change this to something like this then I get error field.Metadata is not defined. It doesn't look like FormElement has a Metadata property
```
public void HandleAction(IActionContext actionContext)
        {

            var jobject = new JObject();
            var myElements = CompiledDefinition.GetElements();

            foreach (var keyValuePair in (IDictionary<string, object>)actionContext.Model)
            {
                var field = myElements.First(e => e is DataFormField df && df.Key == keyValuePair.Key);
                
                if (field.Metadata.TryGetValue("text-checked", out string checkedText))
                {
                    // Do something when serializing
                }

                if (field.Metadata.TryGetValue("text-unchecked", out string uncheckedText))
                {
                    // Do something when serializing
                }

                jobject[keyValuePair.Key] = keyValuePair.Value;
            }
 
        }
```

**Comment by wobbince** [comment]
Have you added the below attributes to the XML?

```XML
meta-text-unchecked="..."
```
```XML
meta-text-checked="..."
```

**Comment by hashitha** [comment]
Yes, but I am getting a compile error

![image](https://user-images.githubusercontent.com/10569142/46845131-aea86100-ce0c-11e8-8967-8310584ad4c6.png)

Doesn't look like FormElement has Metadata field
![image](https://user-images.githubusercontent.com/10569142/46845155-c5e74e80-ce0c-11e8-933c-a98da37042f8.png)

**Comment by edongashi** [comment]
Maybe you have an outdated version, are you using the NuGet build?

**Comment by hashitha** [comment]
Thanks, @edongashi I got it working now. I was using an outdated version. I can't use the NuGet build because of anything above version 2.2.0 of Humanizer.Core breaks our UI for some reason. So I had to change that version in Forge and build.

**Comment by edongashi** [comment]
Thanks for the info, do you have any idea why humanizer is causing problems?
