### ISSUE TITLE
MaterialDesignTextAreaTextBox has changed

### ISSUE THREAD

**Issue by hashitha** [WPF-Forge/Forge.Forms#32]
Looks like `MaterialDesignTextAreaTextBox `has been changed to `MaterialDesignOutlinedTextFieldTextBox` in the latest version of MaterialDesignThemes. This is used in https://github.com/WPF-Forge/Forge.Forms/blob/master/Forge.Forms/src/Forge.Forms/Themes/Material/Field.MultiLineString.xaml

**Comment by edongashi** [comment]
Did this change make forge.forms incompatible with latest mdinxaml?

**Comment by hashitha** [comment]
Sorry, I am not sure what mdinxaml is.

all I did was build the latest forge code and update our project MaterialDesignThemes to latest version 2.5.0.1205 and it was incompatible. So I changed the Field.MultiLineString.xaml and it worked

**Comment by edongashi** [comment]
I see, should we update dependencies and that resource reference?

**Comment by edongashi** [comment]
I am having trouble reproducing this. I updated to latest MDIX but I'm still getting errors when I try to reference `MaterialDesignOutlinedTextFieldTextBox`
