### ISSUE TITLE
DynamicForm not showing validation messages

### ISSUE THREAD

**Issue by skadefro** [WPF-Forge/Forge.Forms#39]
I got inspired by your example application and embedded a side by side showing XML and the form, using DynamicForm, but it doesn't not show the message from validate when validation fails. 
Did I missing something obviuse or is that just not supported in DynamicForm ? 
![image](https://user-images.githubusercontent.com/4155937/62322241-e61ff100-b4a4-11e9-878f-2d497eee9f94.png)

**Comment by edongashi** [comment]
Hi @skadefro.

You aren't doing anything wrong. Looks like you are using the default WPF template. It's a little neglected and the UX may not be ideal. The default WPF textbox error template has no error messages by default. [Here](http://www.skimedic.com/blog/post/2009/07/15/IDataErrorInfo-Error-Templates-and-WPF.aspx) is an article that touches upon error templates.

You can customize the theme for desired controls by providing custom templates or using a theme pack like material or metro (metro is also a little behind). You can see default themes [here](https://github.com/WPF-Forge/Forge.Forms/tree/master/Forge.Forms/src/Forge.Forms/Themes) for reference. The demo uses material theme.

For anything custom you can create ControlTemplates for various controls. For example for single-line textbox you must provide a `ControlTemplate` for type `StringPresenter`. Here you can find default ones for [WPF](https://github.com/WPF-Forge/Forge.Forms/blob/master/Forge.Forms/src/Forge.Forms/Themes/Wpf/Field.String.xaml), [Material](https://github.com/WPF-Forge/Forge.Forms/blob/master/Forge.Forms/src/Forge.Forms/Themes/Material/Field.String.xaml), and [Metro](https://github.com/WPF-Forge/Forge.Forms/blob/master/Forge.Forms/src/Forge.Forms/Themes/Metro/Field.String.xaml) on which you can base your implementation. This can be done externally without modifying any code of this library, just like you can create custom templates for buttons etc in WPF.

Please let me know if anything is unclear.

**Comment by skadefro** [comment]
Thank you very much for a good explanation. I will start by using a theme and then later see if creating custom controltemplates is better for my use.
