### ISSUE TITLE
Dynamic Grid

### ISSUE THREAD

**Issue by redbaty** [WPF-Forge/Forge.Forms#4]
**In development**

- [ ] Multi-view support
- [ ] Add details support
- [ ] Full dynamic form support
- [x] Add, edit and delete commands
- [x] Improved collection (IList<T>)
~~Dialog nesting support (?)~~ (Disabled due to material design guidelines)

**Comment by EdonGashi** [comment]
Add/Update options:

- via dialogs
- via dialog windows
- modify the control to display a different view?

There should be something like IDialogStrategy by which we could make the interaction abstract

**Comment by edongashi** [comment]
Closing for now due to the massive scale of this feature.
