### ISSUE TITLE
Form not building multiple columns

### ISSUE THREAD

**Issue by diegosiao** [WPF-Forge/Forge.Forms#44]
According the documentation this code below should render 2 inputs side by side.. that is not happening...

```
[Field(Row = "Registration", Column = 1)]
public DateTime? Date1 { get; set; }

[Field(Row = "Registration", Column = 2)]
public DateTime? Date2 { get; set; }
```

They are not rendered at all...

**Comment by edongashi** [comment]
Hi @diegosiao! Maybe you need to define the grid first for your form like in this example https://github.com/WPF-Forge/Forge.Forms/blob/master/Forge.Forms/src/Forge.Forms.Demo/Models/DataTypes.cs#L7

Could you please test if this fixes your problem?

**Comment by edongashi** [comment]
I think you may be using default WPF theme, which does not appear to offer a control for `DateTime`. The solution would be implementing a theme for it, or using Metro/Material.

**Comment by diegosiao** [comment]
Hi @edongashi! Worked like a charm! Thanks!

Can I ask you if I can find in examples something using a select with dynamic options?

**Comment by edongashi** [comment]
I found the following examples related to selection:

- [Selection.cs](https://github.com/WPF-Forge/Forge.Forms/blob/master/Forge.Forms/src/Forge.Forms.Demo/Models/Selection.cs)
- [FoodSelection.cs](https://github.com/WPF-Forge/Forge.Forms/blob/master/Forge.Forms/src/Forge.Forms.Demo/Models/FoodSelection.cs)
- [SelectionMemberPaths.cs](https://github.com/WPF-Forge/Forge.Forms/blob/master/Forge.Forms/src/Forge.Forms.Demo/Models/SelectionMemberPaths.cs)

You can open the demo app to interact with them and also see the source code of those you need.

**Comment by diegosiao** [comment]
Thanks once again @edongashi! 
I am delivering an app 10x faster because of this awesome library! 
Closing the issue...

**Comment by edongashi** [comment]
Happy to hear that! Hopefully in the future we can rework it so people aren't forced to use themes if they don't want to.
