### ISSUE TITLE
Workaround for IsDefault and Enter issue

### ISSUE THREAD

**Issue by edongashi** [WPF-Forge/Forge.Forms#5]
The current solution to force all bindings to flush is not ideal. Sooner or later it will cause some unexpected issue. For example if I want to Cancel some dialog, the non-valid controls get a red outline.

One idea of a workaround would be flushing only the focused element, or maybe forcing an unfocus/refocus of the control.

**Comment by redbaty** [comment]
> One idea of a workaround would be flushing only the focused element, or maybe forcing an unfocus/refocus of the control.

Wouldn't this still trigger a red outline on the focused element?

**Comment by EdonGashi** [comment]
Better on the focused than the entire form :laughing:

**Comment by redbaty** [comment]
@EdonGashi 😄 the only other solution would be to use the snapshots, I think at least, or we would need to update the source without validation
