### ISSUE TITLE
Wiki topics

### ISSUE THREAD

**Issue by edongashi** [WPF-Forge/Forge.Forms#9]
- [ ] Annotations
- [ ] Control layout
- [ ] ModelState API
- [ ] Themes and styles
- [ ] Building custom controls
- [ ] Form building internals
- [ ] XML
- [ ] Hooks and interceptors
- [ ] DynamicDataGrid
- [x] Environments
- [x] Binding syntax
- [x] Validation

**Comment by EdonGashi** [comment]
Hey, yeah we have exactly that, there is a demo item with dialogs for reference.

Syntax is like this `Show.Dialog().For<Login>()` plus overloads. Show.Dialog and Window accept additional settings related to the hosting component.

**Comment by EdonGashi** [comment]
Here is the code https://github.com/WPF-Forge/Forge.Forms/blob/master/Forge.Forms/src/Forge.Forms.Demo/Models/Dialogs.cs

**Comment by hashitha** [comment]
@EdonGashi thanks will give this ago. I sent you a message from your website.

**Comment by EdonGashi** [comment]
Just saw it, ill respond in email. I'll also send you a slack invite of the project chat
